# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 07:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('last_transaction', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('last_transaction', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
            ],
        ),
    ]
