# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 19:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellar_adapter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=12, null=True)),
                ('issuer', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
            ],
        ),
    ]
