# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stellar_adapter', '0003_auto_20160920_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='type',
            new_name='code',
        ),
    ]
